### ISSUE TITLE
(Question) No bugs!

### ISSUE THREAD

**Issue by 5c0tt1** [copchase/nightbot_js#7]
Hey @copchase !
I want to make an API so looked for some good examples on Github and found yours!
Whilst mine is completely different (I just want to answer multiple questions streamers are commonly asked), I looked for references and your "rigged" 8ball is **AMAZING!**, as a moderator I have always wanted to rig `!love`, `!hate`, or `!fight` type commands!
I wanted to give it a go first, so I  tried adding a test command using `$(urlfetch https://github.com/copchase/nightbot_js/blob/master/8ball_tsm_theoddone.js)` but this is obviously wrong.
What I was wondering is how would I correct this?
A) Would love to know how to `$(urlfetch)` from Github correctly.
B) Would love to try out a "rigged" command!!

Thank you!

**Comment by copchase** [comment]
Hi @5c0tt1,

To answer your questions,

A) Your command only does half of what is required. You need to both fetch the script and then tell Nightbot to evaluate it. In addition, you should be fetching the raw file, instead of the file embedded within GitHub's interface. Try using this instead: `$(eval $(urlfetch json https://raw.githubusercontent.com/copchase/nightbot_js/master/8ball_tsm_theoddone.js))`

B) I do not completely understand what your question or request is here. Could you please clarify?

**Comment by 5c0tt1** [comment]
Sorry for confusing you with question **B**, I just mean with your answer, I would learn to do both: **A** (urlfetch from github) and **B** (get to use a rigged command!). You kindly answered both! So thank you! now I can start my "questions" api and know how to fetch it from Github correctly.

Anyway, I added your rigged 8ball with the correct syntax you showed in your answer and its working perfectly! I am just unsure how I rig the results though, is it:
- `!ball [WEIGHT] (QUESTION)` e.g `!8ball 90 does nightbot love me?`
- `!8ball [CONSTANT] (QUESTION)` e.g `!8ball negative does nightbot love me?`
- Something else?

**THANK YOU SO MUCH @copchase! ITS APPRECIATED!**

**Comment by copchase** [comment]
It's no problem! The script is actually pre-rigged, and so the command syntax for use on Nightbot is just `!8ball (QUESTION)`. To help understand how it's being rigged, let's go through a breakdown of how the command works:

1. `!8ball` is called, and the script begins execution
2. The file starts at [line 540](https://github.com/copchase/nightbot_js/blob/82e2078da75b6a4f21282f7dea539c3f496c19ef/8ball_tsm_theoddone.js#L540), calling the [`eightball()` function](https://github.com/copchase/nightbot_js/blob/82e2078da75b6a4f21282f7dea539c3f496c19ef/8ball_tsm_theoddone.js#L518)
3. The `eightball()` function then rolls the dice to determine what type of response should be used, which is either a positive response, negative response, a "stupid question" response, or a neutral response
4. After determining the response type, the script rolls the dice again for what specific response should be used with [`weighted_pick()`](https://github.com/copchase/nightbot_js/blob/82e2078da75b6a4f21282f7dea539c3f496c19ef/8ball_tsm_theoddone.js#L500). Each response has a weight determining the chances for it to appear, with a higher weight giving higher chance
5. Finally, return the response, which Nightbot will write in a message

Please do note that anything after `!8ball` is actually not needed, so just calling `!8ball` by itself will run the script without a problem.

Now if you wanted to read the user's input, allowing the user to rig the category of message themselves, such as in your example of `!8ball [CONSTANT] (QUESTION)`, you would need to tell Nightbot to pass the query string to the script. You can do this by changing the Nightbot command to

```$(eval input=decodeURIComponent(`$(querystring)`); $(urlfetch json https://raw.githubusercontent.com/copchase/nightbot_js/master/8ball_tsm_theoddone.js))```. 

You could then call a function using the variable `input` in the script, such as `eightball(input)`. You can actually see an example of this in [slapyou_trambes.js](https://github.com/copchase/nightbot_js/blob/master/slapyou_trambes.js) and [slapyou_tsm_theoddone.js](https://github.com/copchase/nightbot_js/blob/master/slapyou_tsm_theoddone.js).

[Here is also a list of possible variables for Nightbot to pass to the script](https://docs.nightbot.tv/commands/variableslist)
